Repository KimJoongHyeok/ShareComma-Project, pull requests merged in 2021-11, with the labels that each got.

#6 폴더경로 정리
  src/main/webapp/WEB-INF/lib/cos.jar
  src/main/webapp/board/list.jsp
  src/main/webapp/board/post-detail.jsp
  src/main/webapp/board/reservation.jsp
  src/main/webapp/board/update-board-form.jsp
  src/main/webapp/board/write-form.jsp
  src/main/webapp/error/error.jsp
  src/main/webapp/header.jsp
  src/main/webapp/house/house-detail.jsp
  src/main/webapp/layout.jsp
  src/main/webapp/member/login-fail.jsp
  src/main/webapp/member/register-member-form.jsp
  src/main/webapp/member/update-member-form.jsp
Labels: documentation

#7 feat/basic-setting
  .gitignore
  src/main/java/org/kosta/ShareCommaProject/controller/FrontControllerServlet.java
  src/main/java/org/kosta/ShareCommaProject/model/DataSourceManager.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseVO.java
  src/main/java/org/kosta/ShareCommaProject/model/ImageVO.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberVO.java
  src/main/java/org/kosta/ShareCommaProject/model/ReservationDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/ReservationVO.java
Labels: enhancement

#10 hotfix-ReservationVO 수정
  src/main/java/org/kosta/ShareCommaProject/model/ReservationVO.java
Labels: fix

#12 Feat/reservation
  src/main/java/org/kosta/ShareCommaProject/controller/RegisterHouseController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/ImageDAO.java
  src/main/webapp/error.jsp
  src/main/webapp/test/test-ljm.jsp
Labels: enhancement

#14 Feat/update
  src/main/java/org/kosta/ShareCommaProject/controller/DeleteMemberController.java
  src/main/java/org/kosta/ShareCommaProject/controller/UpdateMemberFormController.java
  src/main/java/org/kosta/ShareCommaProject/controller/UpdaterMemberController.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberDAO.java
  src/main/webapp/header.jsp
  src/main/webapp/layout.jsp
  src/main/webapp/member/register-member-form.jsp
  src/main/webapp/member/update-member-form.jsp
Labels: enhancement

#16 Feat/updatehouse
  src/main/java/org/kosta/ShareCommaProject/controller/UpdateHouseController.java
  src/main/java/org/kosta/ShareCommaProject/controller/UpdateHouseFormController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/ImageDAO.java
  src/main/webapp/board/update-board-form.jsp
  src/main/webapp/board/update-house-form.jsp
  src/main/webapp/test-ljm.jsp
Labels: enhancement

#19 Feat/reservation
  src/main/java/org/kosta/ShareCommaProject/controller/ReservateHouseController.java
  src/main/java/org/kosta/ShareCommaProject/controller/ReservateHouseFormController.java
  src/main/java/org/kosta/ShareCommaProject/model/ReservationDAO.java
  src/main/webapp/board/reservation-form.jsp
  src/main/webapp/board/reservation-ok.jsp
  src/main/webapp/test-ljm.jsp
Labels: enhancement

#20 Feat/login
  src/main/java/org/kosta/ShareCommaProject/controller/LoginController.java
  src/main/java/org/kosta/ShareCommaProject/controller/LogoutController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberDAO.java
  src/main/webapp/member/login-fail.jsp
Labels: enhancement

#22 Feat/house list
  src/main/java/org/kosta/ShareCommaProject/controller/HouseListController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/webapp/board/list.jsp
  src/main/webapp/image/cinqueterre.jpg
Labels: enhancement

#25 Feat/host
  src/main/java/org/kosta/ShareCommaProject/controller/BecomeHostController.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberDAO.java
  src/main/webapp/board/list.jsp
  src/main/webapp/member/update-member-form.jsp
Labels: good first issue

#27 FrontController 수정 - ajax
  src/main/java/org/kosta/ShareCommaProject/controller/FrontControllerServlet.java
Labels: good first issue

#32 Css/update member
  src/main/java/org/kosta/ShareCommaProject/controller/BecomeMemberController.java
  src/main/java/org/kosta/ShareCommaProject/model/MemberDAO.java
  src/main/webapp/header.jsp
  src/main/webapp/member/update-member-form.jsp
Labels: css

#33 Css/test register house
  src/main/webapp/board/register-house-form.jsp
  src/main/webapp/header.jsp
Labels: css

#35 Feat/house board detail
  src/main/java/org/kosta/ShareCommaProject/controller/HouseDetailController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/webapp/board/house-detail.jsp
  src/main/webapp/board/list.jsp
  src/main/webapp/board/reservation-form.jsp
  src/main/webapp/header.jsp
  src/main/webapp/layout.jsp
Labels: css

#34 error.jsp CSS 추가 및 수정
  src/main/webapp/error.jsp
Labels: css

#36 header.jsp 회원아이콘 추가
  src/main/webapp/header.jsp
Labels: css

#37 Css/refac
  src/main/webapp/board/imguploadzhong.jpg
  src/main/webapp/board/post-detail.jsp
  src/main/webapp/board/reservation-form.jsp
  src/main/webapp/board/write-form.jsp
  src/main/webapp/house/house-detail.jsp
  src/main/webapp/test-ljm.jsp
  src/main/webapp/test/test-lsh.jsp
Labels: css

#38 Feat/register check
  src/main/java/org/kosta/ShareCommaProject/controller/IdCheckController.java
  src/main/webapp/member/register-member-form.jsp
Labels: enhancement

#39 Feat/house detail jstl
  src/main/java/org/kosta/ShareCommaProject/controller/HouseDetailController.java
  src/main/java/org/kosta/ShareCommaProject/controller/ReservateHouseFormController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/webapp/board/house-detail.jsp
  src/main/webapp/board/list.jsp
  src/main/webapp/board/reservation-form.jsp
  src/main/webapp/header.jsp
  src/main/webapp/layout.jsp
Labels: enhancement, css

#44 Revert "Test/list2"
  src/main/webapp/board/list.jsp
  src/main/webapp/test2.jsp
Labels: css

#46 house-detail.jsp 수정
  src/main/webapp/board/house-detail.jsp
Labels: css

#47 회원가입시 MEMBER 디폴트 값 추가
  src/main/webapp/member/register-member-form.jsp
Labels: enhancement

#49 Test/new
  src/main/webapp/board/list.jsp
  src/main/webapp/test2.jsp
Labels: css

#51 Hotfix/detail
  src/main/java/org/kosta/ShareCommaProject/controller/RegisterHouseController.java
  src/main/java/org/kosta/ShareCommaProject/controller/UpdateHouseController.java
  src/main/java/org/kosta/ShareCommaProject/controller/UpdateHouseFormController.java
  src/main/java/org/kosta/ShareCommaProject/model/HouseBoardDAO.java
  src/main/webapp/assets/css/style.css
  src/main/webapp/board/house-detail.jsp
  src/main/webapp/board/list.jsp
  src/main/webapp/board/reservation-ok.jsp
  src/main/webapp/board/update-house-form.jsp
  src/main/webapp/header.jsp
  src/main/webapp/layout.jsp
  src/main/webapp/member/register-result.jsp
  src/main/webapp/test2.jsp
  src/main/webapp/upload/9915923B5CF8CB5F26104529644310570510725.jpeg
  src/main/webapp/upload/b72e34b3-4ded-49a4-8ac6-54d37c5a98aa111257347026514900933.jpeg
  src/main/webapp/upload/image_readtop_2021_957449_16336942774810377111526319848702186828.jpeg
  src/main/webapp/upload/images104804331889660118719.jpeg
  src/main/webapp/upload/unnamed105010729555579321587.jpeg
  src/main/webapp/upload/재귀당-h2j4-공동-주택-1105049024867526538795.jpeg
Labels: enhancement
